# Generated by Django 6.0.1 on 2026-01-28 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
